apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: maven-docker
  name: maven-docker
  namespace: default  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-docker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: maven-docker
    spec:
      containers:
      - image: kronstonedoc/mavendockernew:latest
        imagePullPolicy: Always
        name: maven-docker

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: maven-docker
  name: maven-docker
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: maven-docker
  ##sessionAffinity: None
  type: ClusterIP